# Generated by Django 4.0.4 on 2022-05-11 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='published_time',
        ),
    ]
