# Generated by Django 4.0.4 on 2022-05-11 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_created_date_comment_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
